defaults:
  - institution: ${institution}
  - curso: ${curso}
  - _self_


docente: Dr. en C. Omar Piña Ramírez
email: opina.ramirez@izt.uam.mx
task: syllabus


constantes:
  dias:
    Monday: lunes
    Tuesday: martes
    Wednesday: miércoles
    Thursday: jueves
    Friday: viernes
    Saturday: sábado
    Sunday: domingo
  meses:
    January: enero
    February: febrero
    March: marzo
    April: abril
    May: mayo
    June: junio
    July: julio
    August: agosto
    September: septiembre
    October: octubre
    November: noviembre
    December: diciembre